<a href="https://colab.research.google.com/github/ShivaniSingh12219767/Python/blob/main/Foundation_Of_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Matrix inverse
A = np.array([[1,2,1],
 [4,4,5],
  [6,7,7]])
A_inverse = np.linalg.inv(A)  # If inverse is not valid then it will give error
print(A_inverse)

[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


In [ ]:
I = A_inverse @ A   # Dot Product
np.round(I)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [ ]:
# Matrix Transpose
A = np.array([[1,2],
              [3,4],[5,6]])


In [ ]:
A.shape

(3, 2)

In [ ]:
mat_transpose = A.T
mat_transpose

array([[1, 3, 5],
       [2, 4, 6]])

In [12]:
B = A = np.array([[0,2],
                 [1,4]])
A*B     # Hadamard Product

array([[ 0,  4],
       [ 1, 16]])

In [13]:
np.multiply(A,B)   # Multiplication of A and B

array([[ 0,  4],
       [ 1, 16]])

In [19]:
#Gaussian Elemenation Method
X = np.array([[1,3,5],[2,2,-1],[1,3,2]])
Y = np.array([[-1],[1],[2]])
print(X)
print()
print(Y)

[[ 1  3  5]
 [ 2  2 -1]
 [ 1  3  2]]

[[-1]
 [ 1]
 [ 2]]


In [22]:
solution = np.linalg.solve(X,Y)
solution                          #In the code snippet you provided, `np.linalg.solve(X, Y)` is solving a system of linear equations. Here's what's happening:

#1. `np` typically stands for NumPy, a popular library for numerical computing in Python.
#2. `np.linalg.solve()` is a function from NumPy's linear algebra module (`np.linalg`). It is used to solve systems of linear equations.
#3. `X` is the coefficient matrix of the system of linear equations.
#4. `Y` is the constant vector in the system of linear equations.

# The `solve()` function finds the solution to the system of linear equations represented by the equation `X * solution = Y`, where `X` is the coefficient matrix, `solution` is the unknown variable vector, and `Y` is the constant vector.

# After calling `np.linalg.solve(X, Y)`, the variable `solution` will contain the solution to the system of linear equations represented by `X` and `Y`.

array([[-2.],
       [ 2.],
       [-1.]])

In [ ]:
# Matrix Basis: A set of n Linearly independent column vectors with n elemnets forms a basis
A = ([[1,0],[0,1]])  # Independent column vectors
B = ([[1,0],[0,1],[1,1]])   # Sum of 1st and 2nd column is equal to 3rd column. Hence Dependent column Vectors