<a href="https://colab.research.google.com/github/ShivaniSingh12219767/Python/blob/main/Foundation_Of_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
# Matrix inverse
A = np.array([[1,2,1],
 [4,4,5],
  [6,7,7]])
A_inverse = np.linalg.inv(A)  # If inverse is not valid then it will give error
print(A_inverse)

[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


In [5]:
I = A_inverse @ A   # Dot Product
np.round(I)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [6]:
# Matrix Transpose
A = np.array([[1,2],
              [3,4],[5,6]])


In [9]:
A.shape

(3, 2)

In [8]:
mat_transpose = A.T
mat_transpose

array([[1, 3, 5],
       [2, 4, 6]])