<a href="https://colab.research.google.com/github/ShivaniSingh12219767/Python/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from io import StringIO
csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,99.0,8.0
10.0,11.0,12.0
32.0,,22.0
43.0,,2.0'''

In [ ]:
df = pd.read_csv(StringIO(csv_data))

In [ ]:
df.isnull().sum()

A    0
B    2
C    0
D    3
dtype: int64

In [ ]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., 99.,  8.],
       [10., 11., 12., nan],
       [32., nan, 22., nan],
       [43., nan,  2., nan]])

In [ ]:
df.dropna(axis=0)        # Drop Row

A    B     C    D
0  1.0  2.0   3.0  4.0
1  5.0  6.0  99.0  8.0

In [ ]:
df.dropna(axis=1)  # Drop Column

A     C
0   1.0   3.0
1   5.0  99.0
2  10.0  12.0
3  32.0  22.0
4  43.0   2.0

In [ ]:
df


A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0  99.0  8.0
2  10.0  11.0  12.0  NaN
3  32.0   NaN  22.0  NaN
4  43.0   NaN   2.0  NaN

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values=np.nan, strategy='most_frequent')  #this line initializes a SimpleImputer object named imr that will replace missing values represented as np.nan with the most frequent value in each column of the dataset.
imr = imr.fit(df.values)                                              # mode
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., 99.,  8.],
       [10., 11., 12.,  4.],
       [32.,  2., 22.,  4.],
       [43.,  2.,  2.,  4.]])

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        , 99.        ,  8.        ],
       [10.        , 11.        , 12.        ,  6.        ],
       [32.        ,  6.33333333, 22.        ,  6.        ],
       [43.        ,  6.33333333,  2.        ,  6.        ]])

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values=np.nan, strategy='median')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., 99.,  8.],
       [10., 11., 12.,  6.],
       [32.,  6., 22.,  6.],
       [43.,  6.,  2.,  6.]])

In [ ]:
df.fillna(df.mean())

A          B     C    D
0   1.0   2.000000   3.0  4.0
1   5.0   6.000000  99.0  8.0
2  10.0  11.000000  12.0  6.0
3  32.0   6.333333  22.0  6.0
4  43.0   6.333333   2.0  6.0

In [ ]:
df.fillna(df.median())      # This fillna method will not work with mode

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0  99.0  8.0
2  10.0  11.0  12.0  6.0
3  32.0   6.0  22.0  6.0
4  43.0   6.0   2.0  6.0

In [ ]:
# Handling the Categorical data
import pandas as pd
df = pd.DataFrame([
    ['green','M',10.1,'class2'],
    ['red','L',13.5,'class1'],
    ['blue','XL',15.3,'class2']
])
df.columns = ['color','size','price','Label']
df

color size  price   Label
0  green    M   10.1  class2
1    red    L   13.5  class1
2   blue   XL   15.3  class2

In [ ]:
size_mapping = {'XL':2,'L':1,'M':0}
df['size'] = df['size'].map(size_mapping)
df


color  size  price   Label
0  green     0   10.1  class2
1    red     1   13.5  class1
2   blue     2   15.3  class2

In [ ]:
inv_size_mapping = {v:k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

In [ ]:
df

color  size  price   Label
0  green     0   10.1  class2
1    red     1   13.5  class1
2   blue     2   15.3  class2

In [ ]:
inv_size_mapping = {v:k for k, v in size_mapping.items()}
df['size'] = df['size'].map(inv_size_mapping) # this code is converting numerical size values in the 'size' column of the DataFrame df to their original categorical labels, assuming that size_mapping contains a mapping from categorical labels to numerical values.
df

color size  price   Label
0  green    M   10.1  class2
1    red    L   13.5  class1
2   blue   XL   15.3  class2

In [ ]:
# Label Encoding
import numpy as np
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['Label']))}
class_mapping

{'class1': 0, 'class2': 1}

In [ ]:
df['Label'] = df['Label'].map(class_mapping)   # Label Encoding
df

color  size  price  Label
0  green     0   10.1      1
1    red     1   13.5      0
2   blue     2   15.3      1

In [ ]:
inv_class_mapping = {v: k for k, v in class_mapping.items()}        # Label Encoding
df['Label'] = df['Label'].map(inv_class_mapping)
df

color  size  price   Label
0  green     0   10.1  class2
1    red     1   13.5  class1
2   blue     2   15.3  class2

In [ ]:
data = pd.read_csv("/content/Iris.csv")
data.head()   # Initial 5 rows

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
data.tail()    # Last 5 rows

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [ ]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]